### ISSUE TITLE
Purpose of check in `c3d::frame`

### ISSUE THREAD

**Issue by Kilidsch** [pyomeca/ezc3d#217]
Hello,

I was looking into speeding up writing C3D-Files from Python and stumbled across the following code in `void ezc3d::c3d::frame( const ezc3d::DataNS::Frame &f, size_t idx)`

```cpp
        std::vector<std::string> labels(parameters().group("POINT")
                                        .parameter("LABELS").valuesAsString());
        for (size_t i=0; i<labels.size(); ++i)
            try {
                pointIdx(labels[i]);
            } catch (std::invalid_argument) {
                throw std::invalid_argument(
                        "All the points in the frame must appear "
                        "in the POINT:LABELS parameter");
            }
```

The frame `f` itself doesn't appear in this check and since `pointIdx` uses `pointNames` and with it indirectly `std::vector<std::string> labels = parameters().group("POINT").parameter("LABELS").valuesAsString();`, it is always going to evaluate to nothing (i.e. no exception being thrown); at least if I don't miss something.

Since this is the computationally most expensive part in the writing process and since it does not _seem_ to have any purpose (anymore?), I wanted to aks, if I can delete this part in a PR?

**Comment by pariterre** [comment]
Hi @Kilidsch !
Thanks for the suggestion! I am currently on vacation and doesn't have access to my computer. If I am not mistaken though, the check is not for the size, but for the name itself (for instance if labels[i] is a label that is not in point, it will raise an error). Of therefore would be required since I don't really have a way to make sure the user did not create an invalid labels structure.
That said, I was thinking, the structure used in the method point that receives the label name could probably be improved, since I am checking by hand the label to convert it in index. Using an hash table for that would probably much faster!

**Comment by Kilidsch** [comment]
Hi @pariterre,

Please feel free to read this answere once your vacation is over! Have a nice vacation!

The thing about this check is that it (at least how I understand it) essentially checks whether `parameters().group("POINT").parameter("LABELS").valuesAsString() == parameters().group("POINT").parameter("LABELS").valuesAsString()`.


The check uses `pointIdx`:
```cpp
size_t ezc3d::c3d::pointIdx(
        const std::string &pointName) const {
    const std::vector<std::string> &currentNames(pointNames());
    for (size_t i = 0; i < currentNames.size(); ++i)
        if (!currentNames[i].compare(pointName))
            return i;
    throw std::invalid_argument("ezc3d::pointIdx could not find "
                                + pointName + " in the points data set.");
}
```

And it uses `pointNames`:
```cpp
const std::vector<std::string> ezc3d::c3d::pointNames() const {
    std::vector<std::string> labels =
            parameters().group("POINT").parameter("LABELS").valuesAsString();
    int i = 2;
    while (parameters().group("POINT").isParameter("LABELS" + std::to_string(i))){
        const std::vector<std::string>& labels_tp
                = parameters().group("POINT").parameter(
                    "LABELS" + std::to_string(i)).valuesAsString();
        labels.insert(labels.end(), labels_tp.begin(), labels_tp.end());
        ++i;
    }
    return labels;
}
```

`pointNames` always returns at least `parameters().group("POINT").parameter("LABELS").valuesAsString()`, so we check if the name is in `POINT::LABELS`. But we're checking  `std::vector<std::string> labels(parameters().group("POINT").parameter("LABELS").valuesAsString()`. So we're checking if every label in `POINT::LABELS` is in `POINT::LABELS`. This is always true.

I hope you could resist reading this immeadiately 😅 If not, I'm sorry. I would have forgotten that reply if I waited...

**Comment by pariterre** [comment]
Hi @Kilidsch !
I turned off my phone not longer after writing you and basically forgot about it for the remaining days haha, so no worry! But if I had actually received the mail, I probably would have had a look hahaha!

I think this check was added when I added the support for more than one LABEL (the new standard allows for LABEL2, LABEL3 and so on). Unfortunately, there is no easy way to make sure LABELS == labels if LABELS is distributed over multiple structures. 

That said, it could probably greatly improved by getting all the name and comparing one time, instead of getting all the names each time the loop is done. I'll make the change today!

**Comment by pariterre** [comment]
Hello again!

I implemented what I just proposed:
```C++
    try {
        // Check if all the labels are in the actual LABELSX parameter
        const std::vector<std::string> &namesParameter(pointNames());
        for (size_t i=0; i<labels.size(); ++i){
            for (size_t i = 0; i < namesParameter.size(); ++i){
                if (!namesParameter[i].compare(labels[i])){
                    break;
                }
            }
        }
    } catch (std::invalid_argument) {
        throw std::invalid_argument(
                "All the points in the frame must appear "
                "in the POINT:LABELS parameter");
    }
```

I've seen that you started to improve on the code speed, that is nice! I suggest you try that snippet to see if it actually improve speed compared to what was there before (it replaces the part you commented with "can I remove this"). If it works, at some point you can open a PR :)

**Comment by Kilidsch** [comment]
Hello @pariterre 

I just tried it and got the following result on writing `Cortex.c3d` to disk (only one run each):

|Method|Time in sec|
|--------|---------|
| old method before my other change | 5.2061723 |
| old method | 2.2334236 |
| your method | 0.4963968000000001 |
| no checking at all | 0.42829680000000003 |

If I am honest, I still don't quite understand why the test is necessary, but since your improved version is only a bit slower than not testing at all, I think I can live with that.

**Comment by pariterre** [comment]
This discussion relates to PR #218 
Thanks for your help, that is a huge improvement in writing time! :)
